### ISSUE TITLE
puiseux_series_ring_element not compiling on sage 7.4 installation

### ISSUE THREAD

**Issue by sjmeagher** [abelfunctions/abelfunctions#137]
I'm using mac os x 10.9.5. I copied all files in my sage directory and ran
./sage -p abelfunctions.spkg
During installation I got the following compile errors (see attached).
It certainly failed as in sage I got an import error "No module named puiseux_series_ring_element" when I ran " from abelfunctions import *".
Thanks
[compileerrors.txt](https://github.com/abelfunctions/abelfunctions/files/572205/compileerrors.txt)

**Comment by cswiercz** [comment]
I haven't tested Abelfunctions on an older version of OSX so I'm not sure what kind of error might come up because of that. However, based on the error output that you attached (thank you very much for doing that!) it looks like you might need a more recent version of Cython.

What version of Sage are you running? Although I haven't tested the build on the absolute most recent version of Sage (I'm sort of transitioning away from this project) I would start by upgrading.

You may also want to try the first installation method described [here](https://github.com/abelfunctions/abelfunctions/blob/master/doc/Installation.md)

**Comment by cswiercz** [comment]
Did you try the first installation technique described [here](https://github.com/abelfunctions/abelfunctions/blob/master/doc/Installation.md)?

Note that it may require installation of the OSX developer tools required by Sage, if you were to build from source. The appropriate excerpt from the Sage `README.md`:

```
>* __OS X:__ Xcode. Make sure you have installed the most recent version  
   of Xcode. With recent versions of OS X (OS X Lion or later), you  
   can install Xcode for free from the App Store. For pre-Lion  
   versions of OS X, you can download Xcode from  
   http://developer.apple.com/downloads/.  

   >* With OS X, you also need to install the "command line tools". When  
   using OS X Mavericks, after installing Xcode, run this command from  
   a terminal window:  

         xcode-select --install

   >* Then click "Install" in the pop-up window.

   >* When using OS X Mountain Lion or earlier, you need to install the  
   command line tools from Xcode: run Xcode; then from the File  
   menu, choose "Preferences", then the "Downloads" tab, and then  
   "Install" the Command Line Tools.  
```

The error you sent me suggests that there is a problem with the version of Cython included with Sage. I haven't tested the build of Abelfunctions with the absolute newest version of Sage. I'm transitioning away from this project in pursuit of an industry job but I will try to address this soon.

**Comment by sjmeagher** [comment]
Thanks for your fast reply, good luck with the job, and let me say your project is amazing and really really valuable - I hope you found some people to maintain it.
I'm running the newest version of sage (7.4). I had to build it from scratch, which involved bypassing the native assembler in mac os (as the newest version of xcode for 10.9.5 doesn't have the newest assembler), and using clang instead with a script.
In fact I only installed the latest version of sage, as the older version I had (6.2), didn't seem to want to install abelfunctions at all.
What is the latest version of sage that definitely works with abelfunctions?
Also what version of cython definitely compiles abelfunctions?
Maybe I can find a fix that way?

**Comment by sjmeagher** [comment]
Also I used the second installation method for abelfunctions. I'll try the first one now.

**Comment by cswiercz** [comment]
> Thanks for your fast reply, good luck with the job, and let me say your project is amazing and really really valuable - I hope you found some people to maintain it.

Thank you for the kind words!

> I'm running the newest version of sage (7.4). I had to build it from scratch, which involved bypassing the native assembler in mac os (as the newest version of xcode for 10.9.5 doesn't have the newest assembler), and using clang instead with a script.
> In fact I only installed the latest version of sage, as the older version I had (6.2), didn't seem to want to install abelfunctions at all.

I'm interested to hear that it was a source installation that had problems. My guess would've been that it would do better than a binary install. I definitely know that versions of Sage below 6.8 don't work because I rely on newer Cython features.

> What is the latest version of sage that definitely works with abelfunctions?

TBD. I'm trying to set up a new and improved Travis-CI config which will include OSX as a build target. Will let you know once that's up and running. You can check the status (once it works) on the [`travisupdates` branch](https://github.com/abelfunctions/abelfunctions/tree/travisupdates). The most recent attempt is [here](https://travis-ci.org/abelfunctions/abelfunctions/builds/173401234). (Obviously the script is broken at the moment. Still figuring out the new Travis-CI features.)

> Also what version of cython definitely compiles abelfunctions? Maybe I can find a fix that way?

I think 0.17 but I'll have to double-check.

**Comment by sjmeagher** [comment]
Tried the first installation method, and that gave almost the same error output.
If it's ok with you, I might ask on the sage google groups about this too? I.e. ask if other people have tried installing, and about compatibility issues with newer versions of cython, also what version of sage last used cython 0.17.

**Comment by cswiercz** [comment]
> Tried the first installation method, and that gave almost the same error output.

Good to know. Thank you for the feedback. 

> If it's ok with you, I might ask on the sage google groups about this too? I.e. ask if other people have tried installing, and about compatibility issues with newer versions of cython, also what version of sage last used cython 0.17.

You're welcome to but just to warn you past inquiries about Abelfunctions on sage-dev have just been forwarded to here. I can give a more definitive answer to the version question soon. 

Thank you for being a build tester for me. A number of people have been experiencing issues with the installation process and only recently have I found time to address them. I don't know what is fundamentally different about my machine so I have been attempting test builds on virtual machines. (In progress.) 

BTW: do you have Xcode installed? Presumably yes since you built Sage from source.

**Comment by cswiercz** [comment]
Ignore the last question. Just re-read your previous comment.

**Comment by cswiercz** [comment]
Some updates:

I finally have a build matrix on Travis-CI across several versions of Sage. See [here](https://travis-ci.org/abelfunctions/abelfunctions/builds/174086183) for details. The result:

**Abelfunctions fails to build on Sage version >7.1**

I'm still going through what possibly changed between versions but it looks like Cython was upgraded to v.0.24 in Sage v.7.2.

I don't have access to Sage v.7.1 for OSX but I'm guessing that this is an os-independent issue. Haven't come up with a fix, yet, but just wanted you to know that I've narrowed down the problem.

**Comment by sjmeagher** [comment]
Thanks, very much appreciated. If there's something I can help with let me know.

**Comment by cswiercz** [comment]
The error has to do with object inheritance in Cython. Particularly, it looks like I haven't or forgot to include the output type in the `cpdef` function definition. So, for example, in Sage's `ModuleElement` class the definition of `_add_` is

```python
cdef class ModuleElement(Element):
    cpdef _add_(self, right)
```

whereas in `PuiseuxSeriesRingElement`, which inherits from `ModuleElement` is defined

```python
cdef class PuiseuxSeries(AlgebraElement):
    cpdef ModuleElement _add_(self, ModuleElement right_m):
```

However, I was trying to copy the way in which Sage's `LaurentSeries` was defined. (`LaurentSeries` contains a `PowerSeries` and a `PuiseuxSeries` contains a `LaurentSeries`.) Taking a closer look at `LaurentSeries` I see my mistake,

```python
cdef class LaurentSeries(AlgebraElement):
    cpdef _add_(self, right_m):
```

I wonder if I made that change for performance purposes. There are a lot of Puiseux series calculations in Abelfunctions and, historically, symbolics plays a high role as a computational bottleneck.

If this is indeed the only issue then I should have a fix by the end of the day. I also noticed that the Sage 7.2 build is timing out on Travis. Hopefully, that issue is related to this one. If not, well, the solution will hopefully just be "don't use Sage 7.2 for now".

### Build Output (Relevant Section)

For my own records and the record of this issue I will post the compile errors I received in my test build. They seem to match yours. The relevant section is shown below. [(Full build output)](https://s3.amazonaws.com/archive.travis-ci.org/jobs/174086186/log.txt)

```
====================================================
Extracting package /home/travis/abelfunctions.spkg
-rw-rw-r-- 1 travis travis 969074 Nov  8 01:22 /home/travis/abelfunctions.spkg
Finished extraction
****************************************************
Host system:
Linux testing-gce-c6f4c88c-94ef-4de6-9fd8-724f334f4323 3.13.0-92-generic #139~precise1-Ubuntu SMP Wed Jun 29 21:30:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/travis/SageMath/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../src/configure --prefix=/home/travis/SageMath/local --with-local-prefix=/home/travis/SageMath/local --with-gmp=/home/travis/SageMath/local --with-mpfr=/home/travis/SageMath/local --with-mpc=/home/travis/SageMath/local --with-system-zlib --disable-multilib --disable-nls --enable-languages=c,c++,fortran --disable-libitm  
Thread model: posix
gcc version 4.9.3 (GCC) 
****************************************************
WARNING: spkg-install is not executable, making it executable
running build_ext
cythoning abelfunctions/complex_path.pyx to abelfunctions/complex_path.c
building 'abelfunctions.complex_path' extension
C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -fPIC
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/abelfunctions
compile options: '-I/home/travis/SageMath/local/include -I/home/travis/SageMath/local/include/python2.7 -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/lib/python2.7/site-packages -I/home/travis/SageMath/local/lib/python2.7/site-packages/sage/ext -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/include/python2.7 -c'
extra options: '-std=c99 -w'
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are installed.
gcc: abelfunctions/complex_path.c
gcc -pthread -shared -L/home/travis/SageMath/local/lib -Wl,-rpath,/home/travis/SageMath/local/lib -L/home/travis/SageMath/local/lib -Wl,-rpath,/home/travis/SageMath/local/lib build/temp.linux-x86_64-2.7/abelfunctions/complex_path.o -L/home/travis/SageMath/local/lib -lpython2.7 -o /home/travis/SageMath/local/var/tmp/sage/build/abelfunctions/abelfunctions/complex_path.so
cythoning abelfunctions/riemann_surface_path.pyx to abelfunctions/riemann_surface_path.c
building 'abelfunctions.riemann_surface_path' extension
C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -fPIC
compile options: '-I/home/travis/SageMath/local/include -I/home/travis/SageMath/local/include/python2.7 -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/lib/python2.7/site-packages -I/home/travis/SageMath/local/lib/python2.7/site-packages/sage/ext -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/include/python2.7 -c'
extra options: '-std=c99 -w'
gcc: abelfunctions/riemann_surface_path.c
gcc -pthread -shared -L/home/travis/SageMath/local/lib -Wl,-rpath,/home/travis/SageMath/local/lib -L/home/travis/SageMath/local/lib -Wl,-rpath,/home/travis/SageMath/local/lib build/temp.linux-x86_64-2.7/abelfunctions/riemann_surface_path.o -L/home/travis/SageMath/local/lib -lpython2.7 -o /home/travis/SageMath/local/var/tmp/sage/build/abelfunctions/abelfunctions/riemann_surface_path.so
cythoning abelfunctions/puiseux_series_ring_element.pyx to abelfunctions/puiseux_series_ring_element.c
Error compiling Cython file:
------------------------------------------------------------
...
        g = gcd(QQ(1)/m,QQ(1)/n).denominator()
        m = g/m
        n = g/n
        return g, m, n
    cpdef ModuleElement _add_(self, ModuleElement right_m):
         ^
------------------------------------------------------------
abelfunctions/puiseux_series_ring_element.pyx:340:10: Signature not compatible with previous declaration
Error compiling Cython file:
------------------------------------------------------------
...
cdef class ModuleElement(Element)       # forward declaration
cdef class RingElement(ModuleElement)   # forward declaration
cdef class ModuleElement(Element):
    cpdef _add_(self, right)
               ^
------------------------------------------------------------
/home/travis/SageMath/local/lib/python2.7/site-packages/sage/structure/element.pxd:194:16: Previous declaration is here
Error compiling Cython file:
------------------------------------------------------------
...
        l1 = LaurentSeries_V(self.__l, m)
        l2 = LaurentSeries_V(right.__l, n)
        l = l1 + l2
        return PuiseuxSeries(self._parent, l, g)
    cpdef ModuleElement _sub_(self, ModuleElement right_m):
         ^
------------------------------------------------------------
abelfunctions/puiseux_series_ring_element.pyx:351:10: Signature not compatible with previous declaration
Error compiling Cython file:
------------------------------------------------------------
...
cdef class RingElement(ModuleElement)   # forward declaration
cdef class ModuleElement(Element):
    cpdef _add_(self, right)
    cpdef _sub_(self, right)
               ^
------------------------------------------------------------
/home/travis/SageMath/local/lib/python2.7/site-packages/sage/structure/element.pxd:195:16: Previous declaration is here
Error compiling Cython file:
------------------------------------------------------------
...
        l1 = LaurentSeries_V(self.__l, m)
        l2 = LaurentSeries_V(right.__l, n)
        l = l1 - l2
        return PuiseuxSeries(self._parent, l, g)
    cpdef RingElement _mul_(self, RingElement right_r):
         ^
------------------------------------------------------------
abelfunctions/puiseux_series_ring_element.pyx:362:10: Signature not compatible with previous declaration
Error compiling Cython file:
------------------------------------------------------------
...
cdef class AdditiveGroupElement(ModuleElement):
    pass
cdef class RingElement(ModuleElement):
    cpdef _mul_(self, right)
               ^
------------------------------------------------------------
/home/travis/SageMath/local/lib/python2.7/site-packages/sage/structure/element.pxd:214:16: Previous declaration is here
Error compiling Cython file:
------------------------------------------------------------
...
        return PuiseuxSeries(self._parent, self.__l._rmul_(c), self.__e)
    cpdef ModuleElement _lmul_(self, RingElement c):
        return PuiseuxSeries(self._parent, self.__l._lmul_(c), self.__e)
    cpdef RingElement _div_(self, RingElement right_r):
         ^
------------------------------------------------------------
abelfunctions/puiseux_series_ring_element.pyx:379:10: Signature not compatible with previous declaration
Error compiling Cython file:
------------------------------------------------------------
...
cdef class AdditiveGroupElement(ModuleElement):
    pass
cdef class RingElement(ModuleElement):
    cpdef _mul_(self, right)
    cpdef _div_(self, right)
               ^
------------------------------------------------------------
/home/travis/SageMath/local/lib/python2.7/site-packages/sage/structure/element.pxd:215:16: Previous declaration is here
Error compiling Cython file:
------------------------------------------------------------
...
                raise ValueError('Can only exponentiate single term by rational')
            l = LaurentSeries_V(self.__l, numer)
            e = self.__e * int(denom)
        return PuiseuxSeries(self._parent, l, e)
    cpdef int _cmp_(self, Element right_r) except -2:
         ^
------------------------------------------------------------
abelfunctions/puiseux_series_ring_element.pyx:414:10: Signature not compatible with previous declaration
Error compiling Cython file:
------------------------------------------------------------
...
cdef str arith_error_message(x, y, op)
cdef class Element(SageObject):
    cdef Parent _parent
    cpdef _richcmp_(left, right, int op)
    cpdef int _cmp_(left, right) except -2
                  ^
------------------------------------------------------------
/home/travis/SageMath/local/lib/python2.7/site-packages/sage/structure/element.pxd:177:19: Previous declaration is here
building 'abelfunctions.puiseux_series_ring_element' extension
C compiler: gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -fPIC
compile options: '-I/home/travis/SageMath/local/include -I/home/travis/SageMath/local/include/python2.7 -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/lib/python2.7/site-packages -I/home/travis/SageMath/local/lib/python2.7/site-packages/sage/ext -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/include/python2.7 -c'
extra options: '-std=c99 -w'
gcc: abelfunctions/puiseux_series_ring_element.c
abelfunctions/puiseux_series_ring_element.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
abelfunctions/puiseux_series_ring_element.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: Command "gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -fPIC -I/home/travis/SageMath/local/include -I/home/travis/SageMath/local/include/python2.7 -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/lib/python2.7/site-packages -I/home/travis/SageMath/local/lib/python2.7/site-packages/sage/ext -I/home/travis/SageMath/local/lib/python2.7/site-packages/numpy/core/include -I/home/travis/SageMath/local/include/python2.7 -c abelfunctions/puiseux_series_ring_element.c -o build/temp.linux-x86_64-2.7/abelfunctions/puiseux_series_ring_element.o -std=c99 -w" failed with exit status 1
```

**Comment by cswiercz** [comment]
Another minor note: in my previous post I mentioned that Sage's `LaurentSeries` had the following types of operator overloading definitions:

```python
cdef class LaurentSeries(AlgebraElement):
    cpdef _add_(self, right_m):
```

However, this is as of more recent versions of Sage. Apparently, in Sage v.7.2 `LaurentSeries` used the definition,

```python
cdef class LaurentSeries(AlgebraElement):
    cpdef ModuleElement _add_(self, ModuleElement right_m):
```

So I shouldn't be *that* hard on myself. 😃

**Comment by cswiercz** [comment]
Abelfunctions now builds on Sage v>=7.3. The fix has severely impacted performance of Puiseux series, which much of the package relies on. I'm opening a new issue to resolve these performance problems.

Still. It should now work!

**Comment by sjmeagher** [comment]
Thanks Chris, I've been a bit busy in the last week. I just tried to compile the new version on sage 7.4 (I don't have 7.3). It seemed to compile, but then sage raised an import error, saying it couldn't find puiseux_series_ring_element
"from abelfunctions import *
ImportError        
ImportError: No module named puiseux_series_ring_element"
Attached is the build output in case there are clues there, but I couldn't find any obvious ones.
[build output.txt](https://github.com/abelfunctions/abelfunctions/files/596497/build.output.txt)

**Comment by cswiercz** [comment]
@sjmeagher You might need to change out of the top-level `abelfunctions/` directory before running anything. Python/Sage, by default, will look in the directory where you started running Python/Sage for modules named "`abelfunctions`". The built version now resides inside the Sage package directory.

Let me know if this solves the problem.

**Comment by sjmeagher** [comment]
Thanks for your message. Unfortunately I run it in the top level directory (and built it there too), so the issue must be something else. The thing is the error returned suggests it knows what abelfunctions is, but it doesn't not what puiseux_series_ring_element is.

from abelfunctions import riemannsurface
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ebe2e2d6db0e> in <module>()
----> 1 from abelfunctions import riemannsurface

/Users/smeagher/Downloads/sage-7.4/abelfunctions/__init__.py in <module>()
     11 from abelfunctions.abelmap import AbelMap, Jacobian
     12 from abelfunctions.homology import symmetrize_periods
---> 13 from abelfunctions.puiseux import puiseux
     14 from abelfunctions.riemann_constant_vector import RiemannConstantVector
     15 from abelfunctions.riemann_surface import RiemannSurface

/Users/smeagher/Downloads/sage-7.4/abelfunctions/puiseux.py in <module>()
     41 import sympy
     42 
---> 43 from abelfunctions.puiseux_series_ring import PuiseuxSeriesRing
     44 
     45 from sage.all import gcd, xgcd

/Users/smeagher/Downloads/sage-7.4/abelfunctions/puiseux_series_ring.py in <module>()
     35 from sage.rings.all import IntegralDomain, CommutativeRing, Field
     36 
---> 37 from abelfunctions.puiseux_series_ring_element import (
     38     is_PuiseuxSeries,
     39     PuiseuxSeries,

ImportError: No module named puiseux_series_ring_element
