### PR TITLE
Use algebraic e-th roots of unity

### PR DESCRIPTION
**Pull request by nbruin**
remove import of symbolic I and pi and replace their use by constructions that construct e-th roots of unity in QQbar directly

---
I'm surprised this code ever worked. Indeed sage can recognize these symbolic expressions as algebraic:
 
```
     sage: QQbar(exp(2*pi/17*I))
     0.9324722294043558? + 0.3612416661871530?*I

```
It seems that on one version of sage this led to "exactify" working on a symbolic expression, but that seems to be no longer the case. It's better to leave the symbolic ring out of it completely.

### CODE REVIEW

**Comment by cswiercz** [comment]
The code that generated this issue. (For reference.)

```python
sage: R.<x,y>=QQ[]
sage: f=y^2-x^4+1
sage: S=abelfunctions.RiemannSurface(f)
sage: S.genus()
AttributeError: 'sage.symbolic.expression.Expression' object has no attribute 'exactify'
```

A corresponding test will be added.

**Comment by cswiercz** [comment]
As a side note, the above code seems to work in Sage 7.1. I'm updating to 7.2 to see if the problem persists on my machine.

**Comment by nbruin** [comment]
Your observation wrt. 7.1 and 7.2 is correct.
```
sage7.1: parent(QQbar(1)*exp(2*pi*I*1/3))
Algebraic Field
```
versus
```
sage7.2: parent(QQbar(1)*exp(2*pi*I*1/3))
Symbolic Ring
```
The result in 7.2 is probably "more correct", since not everything from the symbolic ring fits in QQbar, but every element of QQbar does fit in the symbolic ring, albeit in a rather useless way -- especially because it doesn't actually *do* that:
```
sage: QQbar(17).sqrt()*exp(2*pi*I*1/3)
TypeError: unsupported operand parent(s) for '*': 'Number Field in I with defining polynomial x^2 + 1' and 'Algebraic Field'
```
Anyway, a good thing is that with the new patch you can avoid the symbolic ring altogether, which is always good news.

**Comment by cswiercz** [comment]
The Sage 7.2 version makes more sense.

I ended up spending most of yesterday trying to get Sage 7.2 properly installed and failed. The `-upgrade 7.2` method failed for some reason.

I managed to get tests to pass in 7.1 and trust that they pass in 7.2 so I'm merging. Thanks again for the contribution!
